#!/usr/bin/python
import sys
if sys.argv[1] == '--about':
	version = '1.0.0'
	print 'version',version
	print 'write by arvinall  http://arvinall.usr.sh'
	print 'this script use axel for download files'
else:
	import subprocess
	def bash(cmd):
	    subprocess.Popen(cmd, shell=True, executable='/bin/bash')
	connections = sys.argv[1]
	for url in sys.argv[2:]:
		bash('axel -v -a -n '+connections+' '+url)
	print 'done'
